app:
  test-emails:
    - test@oopsly.com
    - user1@oopsly.com
    - user2@oopsly.com
    - integration@oopsly.com
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
  flyway:
    baseline-version: -1
    locations: classpath:db/migration, classpath:db/dev
management:
  health:
    mail:
      enabled: false
