/*
 * Copyright 2026 Hao Nguyen Tan
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 */
import React, { useState } from "react";
import { Text, TextInput, TouchableOpacity, View } from "react-native";
import { useRouter } from "expo-router";
import AuthScreenLayout from "@/components/common/AuthScreenLayout";
import AppButton from "@/components/common/AppButton";
import FeedbackMessage from "@/components/common/FeedbackMessage";
import { FirebaseAuthService } from "@/services/FirebaseAuthService";
import { uiTokens } from "@/constants/uiTokens";

export default function FirebaseLoginScreen() {
  const router = useRouter();
  const [method, setMethod] = useState<"email" | "phone">("email");
  const [value, setValue] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const sendCode = async () => {
    setBusy(true); setError(null);
    try {
      if (method === "email") {
        await FirebaseAuthService.sendEmailLink(value.trim());
        router.push({ pathname: "/verification", params: { method, identifier: value.trim() } });
      } else {
        // Firebase phone auth requires an app-verification session generated by
        // the native/web Firebase SDK. The verification page accepts that session.
        router.push({ pathname: "/verification", params: { method, identifier: value.trim() } });
      }
    } catch (e) { setError(e instanceof Error ? e.message : "Could not start sign in"); }
    finally { setBusy(false); }
  };

  return <AuthScreenLayout testID="firebase-login-screen">
    <Text style={{ fontSize: 28, fontWeight: "700", color: uiTokens.text.primary }}>Sign in to Oopsly</Text>
    <Text style={{ marginTop: 8, color: uiTokens.text.muted }}>Use a one-time link or phone code. No password needed.</Text>
    <View style={{ flexDirection: "row", gap: 8, marginTop: 24 }}>
      {(["email", "phone"] as const).map(option => <TouchableOpacity key={option} testID={`login-method-${option}`} onPress={() => { setMethod(option); setValue(""); }} style={{ padding: 12, borderRadius: 10, backgroundColor: method === option ? uiTokens.accent.tint : uiTokens.surface.subtle }}><Text>{option === "email" ? "Email" : "Phone"}</Text></TouchableOpacity>)}
    </View>
    <TextInput testID="login-identifier" accessibilityLabel={method} value={value} onChangeText={setValue} autoCapitalize="none" keyboardType={method === "email" ? "email-address" : "phone-pad"} placeholder={method === "email" ? "name@example.com" : "+1 555 123 4567"} style={{ marginTop: 20, padding: 16, borderWidth: 1, borderColor: uiTokens.border.subtle, borderRadius: 12 }} />
    {error ? <FeedbackMessage testID="firebase-login-error" tone="error" message={error} /> : null}
    <View style={{ marginTop: 20 }}><AppButton testID="send-otp-button" label={method === "email" ? "Send sign-in link" : "Continue with phone"} onPress={sendCode} disabled={!value.trim()} loading={busy} /></View>
  </AuthScreenLayout>;
}
