app:
  test-email:
   - test@oopsly.com
   - user2@oopsly.com
   - user1@oopsly.com

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
