# Copyright 2026 Hao Nguyen Tan
# Licensed under the Apache License, Version 2.0
app:
  features:
    authWithFirebase: false
    authWithJwt: false
    skipAuth: true
spring:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
