plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.8'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.graalvm.buildtools.native' version '0.10.6'
}

group = 'com.app.osmosis'
version = '0.0.1-SNAPSHOT'
description = 'Backend server for Osmosis project'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

ext {
	set('springAiVersion', "1.1.0")
	set('springCloudVersion', "2025.0.0")
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-mail'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-websocket'
//	implementation 'org.springframework.ai:spring-ai-pdf-document-reader'
//	implementation 'org.springframework.ai:spring-ai-starter-model-vertex-ai-embedding'
	implementation 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
	imports {
//		mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}

def composeFile = 'src/main/resources/docker-compose.yml'

tasks.register('composeUp', Exec) {
	group = 'docker'
	description = "Start Docker Compose services using ${composeFile}"
	workingDir = projectDir

	commandLine 'docker', 'compose', '-f', composeFile, 'up', '-d', '--build'
	doLast {
		println "Docker Compose started using ${composeFile}"
	}
}

tasks.register('composeDown', Exec) {
	group = 'docker'
	description = "Stop and remove Docker Compose services using ${composeFile}"
	workingDir = projectDir
	commandLine 'docker', 'compose', '-f', composeFile, 'down', '--volumes', '--remove-orphans'
	doLast {
		println "Docker Compose stopped and removed services from ${composeFile}"
	}
}