plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.8'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.graalvm.buildtools.native' version '0.10.6'
	id 'com.diffplug.spotless' version '8.1.0'
	id 'jacoco'
}
group = 'com.app.oopsly'
version = '0.0.1-SNAPSHOT'
description = 'Backend server for Oopsly project'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

ext {
	set('springAiVersion', "1.1.0")
	set('springCloudVersion', "2025.0.0")
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-mail'
//	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-websocket'
//	implementation 'org.springframework.ai:spring-ai-pdf-document-reader'
//	implementation 'org.springframework.ai:spring-ai-starter-model-vertex-ai-embedding'
	implementation 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation("com.google.api-client:google-api-client:2.7.2")
	implementation 'com.google.auth:google-auth-library-oauth2-http:1.40.0'
	implementation 'io.jsonwebtoken:jjwt:0.13.0'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
	imports {
//		mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}

def composeFile = 'src/main/resources/docker-compose.yml'

tasks.register('composeUp', Exec) {
	group = 'docker'
	description = "Start Docker Compose services using ${composeFile}"
	workingDir = projectDir

	commandLine 'docker', 'compose', '-f', composeFile, 'up', '-d', '--build'
	doLast {
		println "Docker Compose started using ${composeFile}"
	}
}

tasks.register('composeDown', Exec) {
	group = 'docker'
	description = "Stop and remove Docker Compose services using ${composeFile}"
	workingDir = projectDir
	commandLine 'docker', 'compose', '-f', composeFile, 'down', '--volumes', '--remove-orphans'
	doLast {
		println "Docker Compose stopped and removed services from ${composeFile}"
	}
}

jacocoTestReport {
	dependsOn test

	reports {
		xml.required = true
		csv.required = false
		html.outputLocation = layout.buildDirectory.dir('jacocoHtml')
	}
}

jacoco {
	toolVersion = "0.8.13"
}

jacocoTestCoverageVerification {
	dependsOn test

	executionData.setFrom(fileTree(dir: project.buildDir, includes: ['jacoco/*.exec']))

	violationRules {
		rule {
			enabled = true
			element = 'CLASS'
			limit {
				counter = 'CLASS'
				value = 'COVEREDRATIO'
				minimum = 0.9
			}
		}
	}
}

spotless {
	java {
		target 'src/**/*.java'
		importOrder('java', 'javax', 'org', 'com', '')
		removeUnusedImports()
		googleJavaFormat('1.17.0')
				.aosp()
				.reflowLongStrings()
		formatAnnotations()
		toggleOffOn()
		trimTrailingWhitespace()
		endWithNewline()
	}
}