# name: BE - CI

# on:
#   push:
#     branches:
#       - main
#       - release/**
#     paths:
#       - 'api/**'
#       - '.github/workflows/be.yaml'
#   pull_request:
#     branches:
#       - main
#       - release/**
#     paths:
#       - 'api/**'
#       - '.github/workflows/be.yaml'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - uses: actions/setup-java@v4
#         with:
#           distribution: "temurin"
#           java-version: 21
#       - name: gradle caching
#         uses: gradle/actions/setup-gradle@v5
#       - name: Spotless Check
#         working-directory: api
#         run: ./gradlew spotlessCheck
#       - name: Run Unit Tests
#         working-directory: api
#         run: ./gradlew test
#       - name: Run Code Coverage and Verify
#         working-directory: api
#         run: ./gradlew jacocoTestCoverageVerification