name: CI

on:
  push:
    branches:
      - main
      - develop
      - release/**
  pull_request:
    branches:
      - main
      - develop
      - release/**
  schedule:
    - cron: '0 2 * * 0' # weekly Sunday 02:00 UTC

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  security-events: write
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Make ci.sh executable
        run: chmod +x .github/workflows/ci.sh

      - name: Run CI Script
        run: ./.github/workflows/ci.sh
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: halng
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          EVENT_NAME: ${{ github.event_name  }}
          REF: ${{ github.ref }}
